import CayleyBacharach
#print axioms PlaneCubic.AtLeastThree
#print axioms PlaneCubic.AtLeastThree.of_infinite
#print axioms PlaneCubic.CardGT
#print axioms PlaneCubic.CommonZero
#print axioms PlaneCubic.ExactlyMeetIn
#print axioms PlaneCubic.atLeastThree_iff_card
#print axioms PlaneCubic.card_add_one_le
#print axioms PlaneCubic.card_le_seven_of_not_atLeastThree
#print axioms PlaneCubic.cayley_bacharach
#print axioms PlaneCubic.cayley_bacharach_any
#print axioms PlaneCubic.cayley_bacharach_classical
#print axioms PlaneCubic.cayley_bacharach_classical_card
#print axioms PlaneCubic.cayley_bacharach_classical_card8
#print axioms PlaneCubic.cayley_bacharach_classical_fintype
#print axioms PlaneCubic.cayley_bacharach_of_no_common_factor
#print axioms PlaneCubic.cayley_bacharach_of_no_common_factor_any
#print axioms PlaneCubic.classical_conic_case
#print axioms PlaneCubic.classical_line_case
#print axioms PlaneCubic.coeffs_eq_zero_of_forall_three
#print axioms PlaneCubic.conic_line_lemma
#print axioms PlaneCubic.conic_points
#print axioms PlaneCubic.conic_three
#print axioms PlaneCubic.conics_le_one
#print axioms PlaneCubic.conics_le_two
#print axioms PlaneCubic.conics_off_line_ge_two
#print axioms PlaneCubic.cubic_four
#print axioms PlaneCubic.cubics_resid
#print axioms PlaneCubic.det_gram_eq_zero_iff
#print axioms PlaneCubic.det_gram_linMul
#print axioms PlaneCubic.det_gram_linMul_char_two
#print axioms PlaneCubic.eval
#print axioms PlaneCubic.evalC
#print axioms PlaneCubic.evalC_expand
#print axioms PlaneCubic.evalC_linMul
#print axioms PlaneCubic.evalC_smul_vec
#print axioms PlaneCubic.eval_expand
#print axioms PlaneCubic.eval_mulLin
#print axioms PlaneCubic.eval_smul_vec
#print axioms PlaneCubic.exists_conic_off_line
#print axioms PlaneCubic.exists_linMul_of_det_gram_eq_zero
#print axioms PlaneCubic.false_of_conic
#print axioms PlaneCubic.finrank_cubicsThrough_le_two
#print axioms PlaneCubic.finrank_ker_evalMap_eq_two
#print axioms PlaneCubic.finrank_ker_evalMap_eq_two_any
#print axioms PlaneCubic.finrank_ker_ge_of_conic
#print axioms PlaneCubic.finrank_ker_ge_of_line
#print axioms PlaneCubic.finrank_le_three_of_no3
#print axioms PlaneCubic.general_position_of_no_common_factor
#print axioms PlaneCubic.gram
#print axioms PlaneCubic.gram_quadForm
#print axioms PlaneCubic.ker_evalMap_eq
#print axioms PlaneCubic.linMul
#print axioms PlaneCubic.line_comp_of_polar
#print axioms PlaneCubic.line_lemma
#print axioms PlaneCubic.line_lemma_false_zmod_two
#print axioms PlaneCubic.line_lemma_fintype
#print axioms PlaneCubic.line_points
#print axioms PlaneCubic.mem_span_of_eight
#print axioms PlaneCubic.mulLin
#print axioms PlaneCubic.ne_zero_of_pairwise
#print axioms PlaneCubic.no_common_conic_of_exact
#print axioms PlaneCubic.no_common_line_of_exact
#print axioms PlaneCubic.noncollinear_of_irreducible
#print axioms PlaneCubic.pappus_clean
#print axioms PlaneCubic.pappus_generic
#print axioms PlaneCubic.pappus_lines_distinct
#print axioms PlaneCubic.pappus_of_cayley_bacharach
#print axioms PlaneCubic.pascal_clean
#print axioms PlaneCubic.pascal_clean_det
#print axioms PlaneCubic.pascal_generic
#print axioms PlaneCubic.pascal_of_cayley_bacharach
#print axioms PlaneCubic.pascal_points_off_conic
#print axioms PlaneCubic.vanishesAt_smul_iff
#print axioms PlaneCubic
